name: tf_inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6.5
  - pip
  - pip:
    - torch==1.3.1
    - onnx==1.6
    - lumin==0.4.0.1
    - tensorflow==1.6
    - onnx-tf==1.1